"""The command line interface of the package.

Seven subcommands, one per thing a reader of the article is likely to want from
a terminal: ``reproduce`` runs the whole analysis headlessly and writes it out,
``simulate`` generates a virtual cohort, ``fit``, ``test-memoryless`` and
``test-periodicity`` run one estimator or one test on a file, ``cite`` prints
the article and this package in a form a reference manager reads, and ``params``
prints every number the article reports.

This module composes the rest of the package and computes nothing of its own.
Every number it prints comes from [`msrelapse.fit`][msrelapse.fit],
[`msrelapse.model`][msrelapse.model],
[`msrelapse.datasets`][msrelapse.datasets] or ``msrelapse._params.PAPER``, and
an error raised by any of them travels out with its own message rather than
being turned into an exit code here. Argument errors are argparse's, which
prints them to standard error and exits with 2.

The records this package ships and generates are synthetic. ``reproduce`` and
``simulate`` say so on standard output every time, and ``reproduce`` records it
in the file it writes, because the clinical series of the study was never
released and no clinical claim can be read off a twin of it.

A ``reproduce`` run repeats itself. Every random draw it makes, the cohort it
generates and the bootstrap behind the two goodness of fit rows of the closing
table included, comes from one seed, which is the one ``--seed`` names or
[`msrelapse.datasets.SYNTHETIC_SEED`][msrelapse.datasets.SYNTHETIC_SEED] when
it names none, and the file it writes carries that seed beside the numbers. Two
runs of the same command therefore write the same ``numbers.json``, byte for
byte. That file also carries the version of this package that wrote it, the one
``msrelapse --version`` prints, so a reproduction directory says which release
produced it. Each of the two goodness of fit rows is measured once and reported
twice, in the closing table and in the memorylessness block of the written
record, where the statistic and the sample size stand beside the p value: the run
measures the test itself and hands it to
[`msrelapse.datasets.reproduction_table`][msrelapse.datasets.reproduction_table],
so the two readings are one number rather than two draws of one bootstrap.

References
----------
I. Bordi, R. Umeton, V. A. G. Ricigliano, et al., "A mechanistic, stochastic
model helps understand multiple sclerosis course and pathogenesis",
International Journal of Genomics, 2013, doi 10.1155/2013/910321.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Final, get_args

import numpy as np
import pandas as pd

import msrelapse
from msrelapse import _citation, datasets, fit, plots
from msrelapse._params import PAPER
from msrelapse.cohort import CohortSpec, Engine, bordi2013_spec, generate
from msrelapse.fit import Family, MemorylessMethod, PeriodicityMethod
from msrelapse.io import (
    Schema,
    read_durations,
    read_weekly,
    weekly_to_durations,
    write_csv,
)
from msrelapse.model import calibrate

if TYPE_CHECKING:  # pragma: no cover - the names are needed only by the type checker
    from collections.abc import Callable, Sequence

__all__ = ["main"]

_NO_HEALTH: Final = PAPER.state_no_health.value
_HEALTH: Final = PAPER.state_health.value
_STATES: Final = (_NO_HEALTH, _HEALTH)

# The spellings every option that names one of them accepts, taken from the
# types rather than written out again, so that this module cannot drift from the
# modules it calls. The first spelling of each is the default the library
# function itself carries, and it is the default of the option here as well.
_ENGINES: Final = get_args(Engine)
_FAMILIES: Final = get_args(Family)
_MEMORYLESS_METHODS: Final = get_args(MemorylessMethod)
_PERIODICITY_METHODS: Final = get_args(PeriodicityMethod)
_SCHEMAS: Final = get_args(Schema)

# The engine reproduce reads the shipped twin under, written out rather than
# taken as the first spelling above because the choice is load-bearing: the twin
# was generated by this engine, so any other one has to generate a cohort of its
# own rather than read the shipped files.
_RENEWAL: Final[Engine] = "renewal"

# The family whose rate is a rate per week. The rate of the other family is a
# per week probability, which carries no unit, and the printed line says which of
# the two it is holding.
_EXPONENTIAL: Final[Family] = "exponential"

# What --state takes. The two clinical codes are read from PAPER, so the help
# text of the option carries whatever codes the package uses.
_BOTH_STATES: Final = "both"
_STATE_CHOICES: Final = (str(_NO_HEALTH), str(_HEALTH), _BOTH_STATES)

# What --method takes on test-memoryless, beside the four names of the test.
_ALL_METHODS: Final = "all"

# Coverage of the confidence interval when the caller names none, the same
# default msrelapse.fit.fit_durations carries. That option and the three beside
# it, --censoring, --continuity-correction and --bootstrap, restate the defaults
# of that function, and a test in tests/test_cli.py reads them off its signature
# and holds the two sets against each other, so neither can drift unnoticed.
_DEFAULT_CI: Final = 0.95

# Where reproduce writes when the caller names no directory.
_DEFAULT_OUT: Final = Path("reproduction")

# How many of the most relapsing patients reproduce reports a barrier ratio of
# their own for. Equation (7) needs a mean duration above one week in both
# states, which a patient of one or two relapses may well not have, so the
# busiest few are the ones the number means anything for.
_N_BUSIEST: Final = 3

# The reading of memorylessness the two goodness of fit rows of the closing
# table report. The run measures every reading of every state once, and this is
# the one it hands to msrelapse.datasets rather than leaving the table to draw a
# second bootstrap of its own.
_KS_METHOD: Final[MemorylessMethod] = "ks"

# The three readings of the same durations reproduce reports, as the name it
# prints them under, the duration law and whether censoring is honoured. The
# naive reading is the arithmetic of the paper, which counted a remission cut
# short by the end of follow up as though it had ended there, and it is named
# once because the potential is calibrated to that reading and to no other.
_NAIVE_READING: Final = "naive"
_FIT_READINGS: Final[tuple[tuple[str, Family, bool], ...]] = (
    (_NAIVE_READING, "exponential", False),
    ("censored", "exponential", True),
    ("geometric", "geometric", True),
)

# The quantities reproduce reads off the closing table rather than measuring
# again, as the key numbers.json carries each under and the opening of the name
# the table gives it. The table already measures all four from the same record,
# and measuring them a second time here would let the file contradict the table
# printed inside it.
_DERIVED_RANGES: Final[tuple[tuple[str, str], ...]] = (
    ("relapse_duration_range_weeks", "relapse duration range"),
    ("longest_remission_weeks", "longest remission"),
    ("followup_range_weeks", "relapsing-remitting phase range"),
)
_BARRIER_RATIO_QUANTITY: Final = "barrier ratio"

# What the pooled periodicity test of msrelapse.fit calls the two details the
# report reads off it: how many patients the record held, and the prefix every
# count of skipped patients carries, one key per reason they were skipped for.
# Both are read rather than required, so that a detail renamed there costs a dash
# in one printed line and not an exception inside a print helper.
_N_PATIENTS_KEY: Final = "n_patients"
_SKIPPED_PREFIX: Final = "n_skipped_"

_SYNTHETIC_BANNER: Final = (
    "SYNTHETIC DATA. These records were generated by this package. They are not "
    "the clinical series of the study and no clinical claim can be read off them."
)

_TABLE_HEADER: Final = ("quantity", "paper", "reproduced", "within tolerance")
_PARAMS_HEADER: Final = ("name", "value", "unit", "source")


@dataclass(frozen=True)
class _Record:
    """One weekly record together with where the CLI got it from.

    Attributes
    ----------
    weekly : pandas.DataFrame
        The record, in the weekly schema of [`msrelapse.io`][msrelapse.io].
    source : str
        One phrase naming where it came from, for the report and the file.
    synthetic : bool
        Whether the record was generated by this package rather than read from
        a file the caller named.
    provenance : tuple of str
        The lines that say so, empty when the record came from a file.
    engine : {'renewal', 'sde'} or None
        Which generator produced the record, and None when it came from a file,
        where no engine ran and the CLI has nothing to say about how the records
        were made.
    """

    weekly: pd.DataFrame
    source: str
    synthetic: bool
    provenance: tuple[str, ...]
    engine: Engine | None


def main(argv: Sequence[str] | None = None) -> int:
    """Run one subcommand and return the code the process should exit with.

    Parameters
    ----------
    argv : sequence of str, optional
        The arguments to parse, without the program name. The default of None
        reads them from ``sys.argv``.

    Returns
    -------
    int
        0 when the subcommand succeeded. ``reproduce`` returns 1 when a row of
        the closing table that carries a tolerance is outside it.

    Raises
    ------
    SystemExit
        With code 0 when ``--version`` or ``--help`` was given, which argparse
        raises once it has printed, and with code 2 when the arguments do not
        parse, which argparse raises after writing the reason to standard error.

    Examples
    --------
    >>> main(["cite", "--bibtex"])  # doctest: +ELLIPSIS
    @article{bordi2013mechanistic,
    ...
    0
    """
    parser = _build_parser()
    args = parser.parse_args(argv)
    handler: Callable[[argparse.Namespace], int] = args.handler
    return handler(args)


def _build_parser() -> argparse.ArgumentParser:
    """Return the parser of the whole command line, subcommands included.

    Returns
    -------
    argparse.ArgumentParser
        The parser. Every subparser records the function that runs it under
        ``handler``, so that [`main`][msrelapse.cli.main] never branches on the
        subcommand name.
    """
    parser = argparse.ArgumentParser(
        prog="msrelapse",
        description=(
            "Reproduce and extend the stochastic double well model of "
            "relapsing-remitting multiple sclerosis of Bordi et al. 2013."
        ),
    )
    # The installed version, printed on its own so that a reader holding a
    # reproduction directory can hold it against the msrelapse_version key
    # numbers.json carries. The action exits during parsing, before the required
    # subcommand is missed, so the flag stands on its own.
    parser.add_argument(
        "--version",
        action="version",
        version=f"msrelapse {msrelapse.__version__}",
        help="print the version of this package and exit",
    )
    subcommands = parser.add_subparsers(dest="subcommand", required=True, metavar="SUBCOMMAND")
    _add_reproduce(subcommands)
    _add_simulate(subcommands)
    _add_fit(subcommands)
    _add_test_memoryless(subcommands)
    _add_test_periodicity(subcommands)
    _add_cite(subcommands)
    _add_params(subcommands)
    return parser


def _add_reproduce(subcommands: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the subcommand that runs the whole analysis and writes it out."""
    parser = subcommands.add_parser(
        "reproduce",
        help="run the analysis of the paper and write the numbers, records and figures",
        description=(
            "Measure on one weekly record every quantity the paper reports, write the "
            "numbers, the record and the figures to a directory, and print a table. "
            "With neither --data nor --seed nor --engine the shipped synthetic twin is "
            "read; any of the latter two generates a fresh synthetic cohort instead."
        ),
    )
    # A record read from a file was made by whatever made it, so naming an engine
    # beside it asks for something no run can deliver. The two options are refused
    # together rather than one of them being quietly ignored.
    source = parser.add_mutually_exclusive_group()
    source.add_argument(
        "--data",
        type=Path,
        default=None,
        help="weekly CSV to measure instead of the shipped synthetic twin",
    )
    source.add_argument(
        "--engine",
        choices=_ENGINES,
        default=None,
        help=f"which generator produces the cohort, not to be given with --data; an sde "
        f"cohort does not meet the closing table, so that run exits 1 as a matter of "
        f"course (default: {_RENEWAL})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=_DEFAULT_OUT,
        help=f"directory to write into, created if it does not exist (default: {_DEFAULT_OUT})",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help=f"seed of the generated cohort and of every bootstrap in the run, the two of "
        f"the closing table included (default: {datasets.SYNTHETIC_SEED}, the seed of the "
        f"shipped twin)",
    )
    parser.add_argument(
        "--no-figures",
        dest="figures",
        action="store_false",
        help="skip the figures, which need matplotlib",
    )
    parser.set_defaults(handler=_run_reproduce)


def _add_simulate(subcommands: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the subcommand that generates a virtual cohort."""
    parser = subcommands.add_parser(
        "simulate",
        help="generate a virtual cohort and write it as a CSV file",
        description=(
            "Generate a cohort of synthetic relapsing-remitting records from two mean "
            "durations and a follow up length, and write it in one of the three schemas."
        ),
    )
    parser.add_argument("--n", type=int, required=True, help="number of patients")
    parser.add_argument(
        "--tau-health", type=float, required=True, help="mean remission duration, in weeks"
    )
    parser.add_argument(
        "--tau-relapse", type=float, required=True, help="mean relapse duration, in weeks"
    )
    parser.add_argument(
        "--weeks", type=float, required=True, help="length of each patient's record, in weeks"
    )
    parser.add_argument(
        "--engine",
        choices=_ENGINES,
        default=_RENEWAL,
        help="renewal draws durations directly, sde integrates the potential",
    )
    parser.add_argument("--seed", type=int, default=None, help="seed, for a reproducible cohort")
    parser.add_argument(
        "--alpha",
        type=float,
        default=PAPER.alpha_reference.value,
        help="control parameter of the potential, used by the sde engine alone",
    )
    parser.add_argument(
        "--format",
        dest="schema",
        choices=_SCHEMAS,
        default=_SCHEMAS[0],
        help="which shape of the same records to write",
    )
    parser.add_argument(
        "-o",
        "--out",
        type=Path,
        required=True,
        metavar="OUT.csv",
        help="file to write, whose directory is created if it does not exist",
    )
    parser.set_defaults(handler=_run_simulate)


def _add_fit(subcommands: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the subcommand that fits a duration law."""
    parser = subcommands.add_parser(
        "fit",
        help="fit the duration law of one or both states of a durations CSV",
        description=(
            "Fit the durations of each state by maximum likelihood and print the mean, "
            "the rate, the confidence interval and the method behind it."
        ),
    )
    parser.add_argument("durations", type=Path, metavar="DURATIONS_CSV", help="durations CSV")
    _add_state_option(parser)
    parser.add_argument(
        "--family", choices=_FAMILIES, default=_FAMILIES[0], help="which duration law to fit"
    )
    parser.add_argument(
        "--censoring",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="honour the runs cut short by the end of follow up (--no-censoring is the "
        "naive arithmetic of the paper)",
    )
    parser.add_argument(
        "--continuity-correction",
        type=float,
        default=0.0,
        help="weeks taken off every complete duration before an exponential fit",
    )
    parser.add_argument(
        "--ci", type=float, default=_DEFAULT_CI, help="coverage of the confidence interval"
    )
    parser.add_argument(
        "--bootstrap",
        type=int,
        default=0,
        help="resamples behind a percentile interval; 0 uses the Fisher information",
    )
    parser.add_argument("--seed", type=int, default=None, help="seed of the bootstrap")
    parser.set_defaults(handler=_run_fit)


def _add_test_memoryless(subcommands: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the subcommand that tests whether durations carry memory."""
    parser = subcommands.add_parser(
        "test-memoryless",
        help="test whether the durations of a state carry no memory",
        description=(
            "Test the claim of the paper that a duration's chance of ending next week "
            "does not depend on how long it has already lasted, by up to four readings."
        ),
    )
    parser.add_argument("durations", type=Path, metavar="DURATIONS_CSV", help="durations CSV")
    _add_state_option(parser)
    parser.add_argument(
        "--method",
        choices=(*_MEMORYLESS_METHODS, _ALL_METHODS),
        default=_MEMORYLESS_METHODS[0],
        help=f"which reading to apply, or {_ALL_METHODS} for every one of them",
    )
    parser.add_argument("--seed", type=int, default=None, help="seed of the bootstrap")
    parser.set_defaults(handler=_run_test_memoryless)


def _add_test_periodicity(subcommands: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the subcommand that looks for a period in a weekly record."""
    parser = subcommands.add_parser(
        "test-periodicity",
        help="look for a period in the relapse onsets of a weekly record and pool the evidence",
        description=(
            "Build a periodogram of each patient's relapse onsets, test its largest "
            "ordinate and combine the per patient p values by Fisher's method. The series "
            "read is one impulse in every week a relapse starts, not the +1 and -1 state "
            "series: under the memoryless hypothesis of the paper the onsets have a flat "
            "spectrum, so a small p value is evidence of a rhythm in them. The test has "
            "little power at the handful of onsets one record holds, so read a large p "
            "value as no rhythm being visible in these few onsets rather than as evidence "
            "that there is none."
        ),
    )
    parser.add_argument("weekly", type=Path, metavar="WEEKLY_CSV", help="weekly CSV")
    parser.add_argument(
        "--method",
        choices=_PERIODICITY_METHODS,
        default=_PERIODICITY_METHODS[0],
        help="which periodogram to build",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="seed of the permutations behind the lombscargle p value",
    )
    parser.set_defaults(handler=_run_test_periodicity)


def _add_cite(subcommands: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the subcommand that prints the citation."""
    parser = subcommands.add_parser(
        "cite",
        help="print the citation of the article and of this package",
        description="Print the article as a reference and both BibTeX entries.",
    )
    parser.add_argument("--bibtex", action="store_true", help="print only the two BibTeX entries")
    parser.set_defaults(handler=_run_cite)


def _add_params(subcommands: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the subcommand that prints every number the article reports."""
    parser = subcommands.add_parser(
        "params",
        help="print every number the article reports, with its unit and its source",
        description=(
            "Print one row per reported number: its name in this package, its value, "
            "its unit and the place in the article it comes from."
        ),
    )
    parser.set_defaults(handler=_run_params)


def _add_state_option(parser: argparse.ArgumentParser) -> None:
    """Add the --state option to a subparser that reads a durations file."""
    parser.add_argument(
        "--state",
        choices=_STATE_CHOICES,
        default=_BOTH_STATES,
        help=(
            f"{_STATE_CHOICES[0]} for relapse, {_STATE_CHOICES[1]} for remission, "
            f"{_BOTH_STATES} for one line per state"
        ),
    )


def _run_reproduce(args: argparse.Namespace) -> int:
    """Measure every reported quantity on one record, write it out and report.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed arguments of the ``reproduce`` subcommand.

    Returns
    -------
    int
        0 when every row of the closing table that carries a tolerance is inside
        it, and 1 otherwise.

    Raises
    ------
    ImportError
        If the figures were asked for and matplotlib is not installed. The check
        is made before the analysis rather than after it, so that an install
        without the plot extra fails in a second rather than at the end.
    """
    data: Path | None = args.data
    out: Path = args.out
    seed: int | None = args.seed
    engine: Engine | None = args.engine
    figures: bool = args.figures

    # Everything that can fail on the way out is settled before the analysis
    # starts: the directory is created and the figures are checked for, so that
    # an unwritable path or a missing matplotlib costs a second and not a whole
    # run.
    out.mkdir(parents=True, exist_ok=True)
    if figures:
        _require_matplotlib()

    # Every random draw of the run, the cohort included, comes from one seed, so
    # that a reproduction repeats itself. Without --seed that is the seed of the
    # shipped twin, which is the run this package documents its own numbers
    # against.
    effective_seed = datasets.SYNTHETIC_SEED if seed is None else seed
    # Naming either a seed or an engine asks for a cohort of this run's own;
    # naming neither reads the shipped twin, which is the cohort that seed built.
    record = _load_record(
        data,
        engine,
        generate_cohort=seed is not None or engine is not None,
        seed=effective_seed,
    )
    weekly = record.weekly
    durations = weekly_to_durations(weekly)

    fits = _duration_fits(durations)
    # Two rows of the closing table are tests this report prints in full, with
    # the statistic, the count and the per patient detail that no row can carry
    # beside the p value. They are measured here, once, and handed to the table,
    # so that the number under the table and the number inside it are one number
    # and one draw rather than two of each.
    memoryless = _memorylessness(durations, effective_seed)
    periodicity = fit.test_periodicity(weekly, method="fisher_g")
    table = datasets.reproduction_table(
        weekly,
        rng=effective_seed,
        ks_tests={state: result for state, result in memoryless if result.method == _KS_METHOD},
        periodicity=periodicity,
    )
    # The potential is calibrated to the naive means, the ones the paper itself
    # averaged and the ones the closing table compares against, rather than to
    # the censored fit, which estimates the mean of the process behind the record
    # and is the larger of the two.
    naive = {state: result for reading, state, result in fits if reading == _NAIVE_READING}
    # The control parameter is bound once and handed to the fit, so that the value
    # reported beside the asymmetry and the noise is the value they were found at.
    alpha = PAPER.alpha_reference.value
    beta, sigma = calibrate(naive[_HEALTH].mean, naive[_NO_HEALTH].mean, alpha=alpha)
    spans = _spans(table)
    ratio = _reproduced(table, _BARRIER_RATIO_QUANTITY)
    ratios = _busiest_barrier_ratios(durations)
    calibration = {"alpha": alpha, "beta": beta, "sigma": sigma}
    met = _all_within_tolerance(table)

    payload = {
        "source": record.source,
        "synthetic": record.synthetic,
        "provenance": "\n".join(record.provenance) if record.provenance else None,
        "seed": seed,
        "effective_seed": effective_seed,
        "engine": record.engine,
        "citation": _citation.short_citation(),
        # Which release wrote this directory, so that a file found later can be
        # held against the package that produced it.
        "msrelapse_version": msrelapse.__version__,
        "closing_table": table.to_dict(orient="records"),
        "all_within_tolerance": met,
        "fits": [
            {"reading": reading, "state_name": _state_name(state), **dataclasses.asdict(result)}
            for reading, state, result in fits
        ],
        "memorylessness": [
            {"state": state, "state_name": _state_name(state), **dataclasses.asdict(result)}
            for state, result in memoryless
        ],
        "periodicity": dataclasses.asdict(periodicity.pooled),
        "barrier_ratio": {"cohort": ratio, "busiest_patients": ratios},
        **spans,
        "calibration": calibration,
    }

    written = [
        _write_json(out / "numbers.json", payload),
        _write_frame(weekly, out / "weekly.csv"),
        _write_frame(durations, out / "durations.csv"),
    ]
    if figures:
        written.extend(plots.save_all_paper_figures(out, weekly, durations, rng=effective_seed))

    _report_reproduction(record, seed, effective_seed, table)
    _report_measurements(fits, memoryless, periodicity)
    _report_derived(ratio, ratios, spans, calibration)
    print()
    print(f"every judged row of the closing table within tolerance: {_format_value(met)}")
    for path in written:
        print(f"wrote {path}")
    return 0 if met else 1


def _run_simulate(args: argparse.Namespace) -> int:
    """Generate one cohort, write it in the requested schema and report.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed arguments of the ``simulate`` subcommand.

    Returns
    -------
    int
        0, the cohort having been written.

    Raises
    ------
    ValueError
        If the cohort holds no frame in the requested schema.
    """
    schema: str = args.schema
    out: Path = args.out
    spec = CohortSpec(
        n=args.n,
        tau_health=args.tau_health,
        tau_relapse=args.tau_relapse,
        followup_weeks=args.weeks,
        engine=args.engine,
        alpha=args.alpha,
    )
    # The directory is created before the cohort is generated, so that an
    # unwritable or mistyped path costs a moment rather than a whole generation,
    # which under the sde engine is several seconds.
    out.parent.mkdir(parents=True, exist_ok=True)
    cohort = generate(spec, rng=args.seed)
    # The three schema names of msrelapse.io are the three frame attributes of a
    # Cohort, so the frame is read by name rather than through a map written out
    # here that a fourth schema would leave behind.
    frame: pd.DataFrame | None = getattr(cohort, schema)
    if frame is None:
        raise ValueError(
            f"the {spec.engine} engine produced no {schema} frame for this spec, so there is "
            f"nothing to write; ask for the events schema instead"
        )
    write_csv(frame, out)
    print(cohort.provenance)
    print(f"wrote {out} ({len(frame)} rows, {schema} schema)")
    return 0


def _run_fit(args: argparse.Namespace) -> int:
    """Fit the durations of each requested state and print one line per state.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed arguments of the ``fit`` subcommand.

    Returns
    -------
    int
        0, every fit having been printed.
    """
    durations = read_durations(args.durations)
    for state in _states(args.state):
        result = fit.fit_durations(
            durations,
            state,
            family=args.family,
            censoring=args.censoring,
            ci=args.ci,
            bootstrap=args.bootstrap,
            continuity_correction=args.continuity_correction,
            rng=args.seed,
        )
        _print_fit(_state_name(state), result)
    return 0


def _run_test_memoryless(args: argparse.Namespace) -> int:
    """Test each requested state by each requested method and print the results.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed arguments of the ``test-memoryless`` subcommand.

    Returns
    -------
    int
        0, every test having been printed.
    """
    durations = read_durations(args.durations)
    method: str = args.method
    methods = _MEMORYLESS_METHODS if method == _ALL_METHODS else (method,)
    for state in _states(args.state):
        for name in methods:
            result = fit.test_memoryless(durations, state, method=name, rng=args.seed)
            _print_test(_state_name(state), result)
    return 0


def _run_test_periodicity(args: argparse.Namespace) -> int:
    """Look for a period in a weekly record and print the pooled evidence.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed arguments of the ``test-periodicity`` subcommand.

    Returns
    -------
    int
        0, the pooled test having been printed.
    """
    weekly = read_weekly(args.weekly)
    result = fit.test_periodicity(weekly, method=args.method, rng=args.seed)
    _print_periodicity(result)
    return 0


def _run_cite(args: argparse.Namespace) -> int:
    """Print the citation of the article and of this package.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed arguments of the ``cite`` subcommand.

    Returns
    -------
    int
        0, the citation having been printed.
    """
    bibtex: bool = args.bibtex
    if bibtex:
        print(f"{_citation.PAPER_BIBTEX}\n\n{_citation.SOFTWARE_BIBTEX}")
    else:
        print(_citation.citation())
    return 0


def _run_params(args: argparse.Namespace) -> int:
    """Print every number the article reports, with its unit and its source.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed arguments of the ``params`` subcommand, which takes none.

    Returns
    -------
    int
        0, the table having been printed.
    """
    del args
    rows = [
        (
            str(record["name"]),
            _format_value(record["value"]),
            str(record["unit"]),
            str(record["source"]),
        )
        for record in PAPER.as_records()
    ]
    _print_aligned(_PARAMS_HEADER, rows)
    return 0


def _require_matplotlib() -> None:
    """Refuse a run that asks for figures it will not be able to draw.

    Raises
    ------
    ImportError
        If matplotlib is not installed. matplotlib is the ``plot`` extra of
        this package and the figures are the last thing a reproduction writes,
        so an install without the extra would otherwise run the whole analysis
        before failing. The check is
        [`msrelapse.plots.require_matplotlib`][msrelapse.plots.require_matplotlib],
        so that the message a caller reads is the one message that module
        carries.
    """
    plots.require_matplotlib()


def _load_record(
    data: Path | None, engine: Engine | None, *, generate_cohort: bool, seed: int
) -> _Record:
    """Return the weekly record to measure, and say where it came from.

    Parameters
    ----------
    data : pathlib.Path or None
        A weekly CSV to read, or None to use a synthetic record.
    engine : {'renewal', 'sde'} or None
        Which generator produces the synthetic record, or None for the default
        one.
    generate_cohort : bool
        Whether to generate a cohort rather than read the shipped twin. Ignored
        when `data` names a file, which is read whatever else was asked for.
    seed : int
        The seed a generated cohort is drawn from. Generating from a seed rather
        than from None keeps every run repeatable.

    Returns
    -------
    _Record
        The record and its provenance.

    Raises
    ------
    ValueError
        If the generated cohort holds no weekly record, which cannot happen for
        the spec of the paper and is checked so that a future change to that
        spec fails here rather than measuring nothing.
    """
    if data is not None:
        return _Record(read_weekly(data), f"weekly CSV {data}", False, (), None)
    note = datasets.provenance().splitlines()[0]
    if not generate_cohort:
        return _Record(
            datasets.load_synthetic_bordi2013("weekly"),
            "the synthetic twin shipped with this package",
            True,
            (note,),
            _RENEWAL,
        )
    chosen: Engine = _RENEWAL if engine is None else engine
    cohort = generate(bordi2013_spec(chosen), rng=seed)
    if cohort.weekly is None:
        raise ValueError(
            f"the cohort of bordi2013_spec({chosen!r}) holds no weekly record, so there is "
            f"nothing to measure; the spec has to keep weekly=True"
        )
    return _Record(
        cohort.weekly,
        f"a synthetic cohort generated with the {chosen} engine",
        True,
        (note, cohort.provenance),
        chosen,
    )


def _duration_fits(durations: pd.DataFrame) -> list[tuple[str, int, fit.FitResult]]:
    """Fit each state under each of the three readings of the same durations.

    Parameters
    ----------
    durations : pandas.DataFrame
        A frame in the durations schema of [`msrelapse.io`][msrelapse.io].

    Returns
    -------
    list of tuple
        The name of the reading, the clinical code of the state and the fit, one
        entry per state and reading.
    """
    return [
        (reading, state, fit.fit_durations(durations, state, family=family, censoring=censoring))
        for state in _STATES
        for reading, family, censoring in _FIT_READINGS
    ]


def _memorylessness(durations: pd.DataFrame, seed: int) -> list[tuple[int, fit.TestResult]]:
    """Run every reading of memorylessness on every state.

    Parameters
    ----------
    durations : pandas.DataFrame
        A frame in the durations schema of [`msrelapse.io`][msrelapse.io].
    seed : int
        Seed of the bootstrap behind each of the four readings.

    Returns
    -------
    list of tuple
        The clinical code of the state and the test, one entry per state and
        method.
    """
    return [
        (state, fit.test_memoryless(durations, state, method=method, rng=seed))
        for state in _STATES
        for method in _MEMORYLESS_METHODS
    ]


def _spans(table: pd.DataFrame) -> dict[str, object]:
    """Return the three ranges the article reports, read off the closing table.

    Parameters
    ----------
    table : pandas.DataFrame
        The closing table of
        [`msrelapse.datasets.reproduction_table`][msrelapse.datasets.reproduction_table],
        which has already measured all three on the record.

    Returns
    -------
    dict
        Three entries, all in whole weeks:
        ``relapse_duration_range_weeks`` the shortest and longest relapse,
        ``longest_remission_weeks`` the longest remission, and
        ``followup_range_weeks`` the shortest and longest record. They are
        written to ``numbers.json`` under these names.
    """
    return {key: _reproduced(table, quantity) for key, quantity in _DERIVED_RANGES}


def _reproduced(table: pd.DataFrame, quantity: str) -> object:
    """Return what the closing table measured for the one quantity named.

    Parameters
    ----------
    table : pandas.DataFrame
        The closing table of
        [`msrelapse.datasets.reproduction_table`][msrelapse.datasets.reproduction_table].
    quantity : str
        The opening of the name that table gives the quantity.

    Returns
    -------
    object
        The ``reproduced`` entry of that row: a number, or a pair of numbers for
        a range.

    Raises
    ------
    ValueError
        If the table holds no such row or more than one, so that a quantity
        renamed or dropped in [`msrelapse.datasets`][msrelapse.datasets] fails
        here rather than going missing from ``numbers.json``.
    """
    matches = [
        row["reproduced"]
        for row in table.to_dict(orient="records")
        if str(row["quantity"]).startswith(quantity)
    ]
    if len(matches) != 1:
        raise ValueError(
            f"the closing table holds {len(matches)} rows whose quantity opens with "
            f"{quantity!r} and exactly one is needed; msrelapse.datasets.reproduction_table "
            f"has renamed or dropped that row"
        )
    return matches[0]


def _busiest_barrier_ratios(durations: pd.DataFrame) -> dict[str, float]:
    """Return the barrier ratio of the patients with the most relapses.

    Parameters
    ----------
    durations : pandas.DataFrame
        A frame in the durations schema of [`msrelapse.io`][msrelapse.io].

    Returns
    -------
    dict of str to float
        One ratio per patient, keyed by patient_id, for the
        ``_N_BUSIEST`` patients holding the most relapses. A patient whose
        mean duration in either state is one week or shorter gets a missing
        value, because equation (7) is undefined there.
    """
    relapses = durations[durations["state"] == _NO_HEALTH]
    busiest = relapses.groupby("patient_id", sort=True).size().nlargest(_N_BUSIEST).index
    ratios = fit.barrier_ratio(durations, per_patient=True).reindex(busiest)
    return {str(patient): float(value) for patient, value in ratios.items()}


def _all_within_tolerance(table: pd.DataFrame) -> bool:
    """Return whether every judged row of the closing table meets its rule.

    Parameters
    ----------
    table : pandas.DataFrame
        The closing table of
        [`msrelapse.datasets.reproduction_table`][msrelapse.datasets.reproduction_table].

    Returns
    -------
    bool
        True when every row carrying a tolerance is inside it. A row carrying no
        tolerance carries no verdict and is not counted.
    """
    judged = table[table["tolerance"].notna()]
    return all(bool(verdict) for verdict in judged["within_tolerance"])


def _report_reproduction(
    record: _Record, seed: int | None, effective_seed: int, table: pd.DataFrame
) -> None:
    """Print where the record came from and how it did against the closing table.

    Parameters
    ----------
    record : _Record
        The record that was measured.
    seed : int or None
        The seed the caller named, if any.
    effective_seed : int
        The seed every random draw of the run was made from.
    table : pandas.DataFrame
        The closing table of
        [`msrelapse.datasets.reproduction_table`][msrelapse.datasets.reproduction_table].
    """
    if record.synthetic:
        print(_SYNTHETIC_BANNER)
        for line in record.provenance:
            print(line)
        print()
    print(f"source: {record.source}")
    # A record read from a file was made by no engine of this package, and the
    # report says nothing about one rather than naming the default.
    if record.engine is not None:
        print(f"engine: {record.engine}")
    print(f"seed: {'none' if seed is None else seed}")
    # One seed behind every draw, the bootstrap of the two goodness of fit rows
    # of the table below included, so two runs of the same command write the same
    # numbers and this line carries no exception to itself.
    print(f"every random draw of this run uses seed {effective_seed}")
    print()
    rows = [
        (
            str(row["quantity"]),
            _format_value(row["paper"]),
            _format_value(row["reproduced"]),
            _format_value(row["within_tolerance"]),
        )
        for row in table.to_dict(orient="records")
    ]
    _print_aligned(_TABLE_HEADER, rows)


def _report_measurements(
    fits: list[tuple[str, int, fit.FitResult]],
    memoryless: list[tuple[int, fit.TestResult]],
    periodicity: fit.PeriodicityResult,
) -> None:
    """Print the duration fits and the two tests of a reproduction.

    Parameters
    ----------
    fits : list of tuple
        The output of ``_duration_fits``.
    memoryless : list of tuple
        The output of ``_memorylessness``.
    periodicity : msrelapse.fit.PeriodicityResult
        The periodicity test of the same record.
    """
    print("\nduration fits")
    for reading, state, fitted in fits:
        _print_fit(f"{_state_name(state)} {reading}", fitted)
    print("\nmemorylessness tests")
    for state, tested in memoryless:
        _print_test(_state_name(state), tested)
    print("\nperiodicity")
    _print_periodicity(periodicity)


def _report_derived(
    ratio: object,
    busiest: dict[str, float],
    spans: dict[str, object],
    calibration: dict[str, float],
) -> None:
    """Print the barrier ratio, the ranges and the potential the means ask for.

    Parameters
    ----------
    ratio : object
        The barrier ratio of equation (7) over the whole record, as the closing
        table measured it.
    busiest : dict of str to float
        The same ratio for the patients with the most relapses.
    spans : dict
        The output of ``_spans``.
    calibration : dict of str to float
        The control parameter, the asymmetry and the noise of the potential.
    """
    print("\nderived quantities")
    print(f"barrier ratio dV1/dV2, equation (7): cohort={_format_value(ratio)}")
    for patient, value in busiest.items():
        print(f"  {patient}: {_format_value(value)}")
    for name, span in spans.items():
        print(f"{name}: {_format_value(span)}")
    potential = " ".join(f"{name}={_format_value(value)}" for name, value in calibration.items())
    print(f"calibrated potential: {potential}")


def _print_fit(label: str, result: fit.FitResult) -> None:
    """Print one fitted duration law on one line.

    Parameters
    ----------
    label : str
        What the line opens with, up to the colon.
    result : msrelapse.fit.FitResult
        The fit to print.
    """
    # The exponential family fits a rate per week; the geometric family fits a
    # per week success probability, which is a number between 0 and 1 and carries
    # no unit of its own.
    rate_unit = "per week" if result.family == _EXPONENTIAL else "per week, a probability"
    print(
        f"{label}: n={result.n} censored={result.n_censored} "
        f"mean={_format_number(result.mean)} weeks "
        f"rate={_format_number(result.rate)} {rate_unit} "
        f"ci_low={_format_number(result.ci_low)} ci_high={_format_number(result.ci_high)} "
        f"level={_format_number(result.ci_level)} method={result.ci_method} "
        f"family={result.family}"
    )


def _print_test(label: str, result: fit.TestResult) -> None:
    """Print one hypothesis test on one line.

    Parameters
    ----------
    label : str
        What the line opens with, up to the colon.
    result : msrelapse.fit.TestResult
        The test to print.
    """
    print(
        f"{label}: method={result.method} n={result.n} "
        f"statistic={_format_number(result.statistic)} p={_format_number(result.p_value)}"
    )


def _print_periodicity(result: fit.PeriodicityResult) -> None:
    """Print the pooled periodicity test and how many patients it read.

    Parameters
    ----------
    result : msrelapse.fit.PeriodicityResult
        The per patient table and the pooled test.
    """
    pooled = result.pooled
    details = pooled.details
    # Every reason a patient can be skipped for is reported by the pooled test
    # under its own n_skipped_ key, so the reasons are read off the result rather
    # than named here and one added to msrelapse.fit appears without a change.
    skipped = {
        name.removeprefix(_SKIPPED_PREFIX): int(count)
        for name, count in details.items()
        if name.startswith(_SKIPPED_PREFIX)
    }
    _print_test("pooled", pooled)
    reasons = " ".join(f"{name}={count}" for name, count in skipped.items())
    # The pooled test counts one p value per patient it could read, so its own n
    # is how many were tested, and the count below is how many there were. It is
    # read the way the reasons above are read, so that a pooled result that stops
    # reporting it prints a dash rather than failing inside a print helper.
    counted = details.get(_N_PATIENTS_KEY)
    in_record = _format_value(None if counted is None else int(counted))
    print(f"patients: in_record={in_record} tested={pooled.n} ({reasons})")


def _print_aligned(header: Sequence[str], rows: Sequence[Sequence[str]]) -> None:
    """Print a table of strings with its columns lined up under a header.

    Parameters
    ----------
    header : sequence of str
        The column names.
    rows : sequence of sequence of str
        The rows, each holding one cell per column name.
    """
    columns = zip(header, *rows, strict=True)
    widths = [max(len(cell) for cell in column) for column in columns]
    for line in (header, *rows):
        cells = (cell.ljust(width) for cell, width in zip(line, widths, strict=True))
        print("  ".join(cells).rstrip())


def _write_json(path: Path, payload: dict[str, object]) -> Path:
    """Write one record of measurements as JSON and return the file it went to.

    Parameters
    ----------
    path : pathlib.Path
        File to write.
    payload : dict
        The measurements, which are converted by ``_jsonable`` first.

    Returns
    -------
    pathlib.Path
        `path`, so that the caller can list what it wrote.
    """
    text = json.dumps(_jsonable(payload), indent=2)
    path.write_text(f"{text}\n", encoding="utf-8")
    return path


def _write_frame(frame: pd.DataFrame, path: Path) -> Path:
    """Write one frame as a CSV file and return the file it went to.

    Parameters
    ----------
    frame : pandas.DataFrame
        The frame to write, in one of the three schemas of
        [`msrelapse.io`][msrelapse.io].
    path : pathlib.Path
        File to write.

    Returns
    -------
    pathlib.Path
        `path`, so that the caller can list what it wrote.
    """
    write_csv(frame, path)
    return path


def _jsonable(value: object) -> object:
    """Return one measured value in a shape ``json`` can write.

    Parameters
    ----------
    value : object
        A value of the record ``reproduce`` writes: a number, a string, a
        boolean, a tuple, a list, a dictionary or None.

    Returns
    -------
    object
        The same value, with numpy scalars turned into Python ones, tuples into
        lists and non-finite numbers into None, so that the file is valid JSON
        rather than the NaN and Infinity that ``json`` writes by default.

    Raises
    ------
    TypeError
        If `value` is of a kind this function does not know how to write, so
        that a new measurement of an unexpected kind fails here rather than
        reaching the file in a shape nothing can read back.

    Examples
    --------
    >>> _jsonable({"span": (1.0, 2.0), "missing": float("nan")})
    {'span': [1.0, 2.0], 'missing': None}
    """
    if value is None or isinstance(value, (bool, str)):
        return value
    if isinstance(value, np.generic):
        return _jsonable(value.item())
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if isinstance(value, (tuple, list)):
        return [_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    raise TypeError(
        f"the reproduction record holds a {type(value).__name__} at some key, which this "
        f"module does not know how to write as JSON; add a branch to _jsonable for it"
    )


def _states(choice: str) -> tuple[int, ...]:
    """Return the clinical codes one ``--state`` argument asks for.

    Parameters
    ----------
    choice : str
        The argument, one of the two state codes written out or ``'both'``.

    Returns
    -------
    tuple of int
        The codes to work on, relapse first when both are asked for.

    Examples
    --------
    >>> _states("both") == (PAPER.state_no_health.value, PAPER.state_health.value)
    True
    """
    if choice == _BOTH_STATES:
        return _STATES
    return (int(choice),)


def _state_name(state: int) -> str:
    """Return the clinical name of one state code.

    Parameters
    ----------
    state : int
        The code, +1 for no health and -1 for health.

    Returns
    -------
    str
        ``'relapse'`` or ``'remission'``.

    Examples
    --------
    >>> _state_name(PAPER.state_health.value)
    'remission'
    """
    return "relapse" if state == _NO_HEALTH else "remission"


def _format_number(value: float) -> str:
    """Return one number at the six significant digits every printed line uses.

    Parameters
    ----------
    value : float
        The number to print.

    Returns
    -------
    str
        The number, without a trailing zero it does not need.

    Examples
    --------
    >>> _format_number(4.3), _format_number(1.0)
    ('4.3', '1')
    """
    return f"{value:.6g}"


def _format_value(value: object) -> str:
    """Return one measured value as the text a printed table holds.

    Parameters
    ----------
    value : object
        A number, a boolean, a pair of numbers, a string or None.

    Returns
    -------
    str
        The value in words: a dash where there is none, ``'yes'`` or ``'no'``
        for a verdict, and a bracketed pair for a range. A number that is not
        finite is a missing number and reads as the same dash, which is how
        ``_jsonable`` writes it to the file beside the printed table.

    Examples
    --------
    >>> _format_value(None), _format_value(True), _format_value((1.0, 24.0))
    ('-', 'yes', '(1, 24)')
    >>> _format_value(float("nan"))
    '-'
    """
    if value is None:
        return "-"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (tuple, list)):
        return f"({', '.join(_format_value(item) for item in value)})"
    if isinstance(value, float):
        return _format_number(value) if math.isfinite(value) else "-"
    return str(value)


if __name__ == "__main__":  # pragma: no cover - the console script calls main itself
    raise SystemExit(main())
