"""Helpers shared by the tests that read the files of the repository.

Two jobs live here. The first is the small readers several test modules need:
one text reader and three parsers, so that a page, a workflow and a metadata
file are opened the same way everywhere. The second is the house style of the
repository, written once: no em dash, no line of hyphens, no mention of an
assistant or a model, and no Markdown line that ends in a single space. The
sweep in ``tests/test_docs.py`` applies those rules to every text file found by
``text_files``, so a module, a test and a notebook are held to the bar the
prose is held to.
"""

from __future__ import annotations

import json
import os
import re
from functools import cache
from pathlib import Path
from typing import Any, cast

import yaml  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"
GITIGNORE = ".gitignore"

# Directories the sweep never walks into. Version control, the virtual
# environment, the built site and the caches hold nothing written by hand.
SKIPPED_DIRECTORIES = frozenset(
    {
        ".git",
        ".venv",
        "site",
        "node_modules",
        "__pycache__",
        ".ruff_cache",
        ".mypy_cache",
        ".hypothesis",
        ".pytest_cache",
    }
)

# The copy of the article under docs/ is a download from the publisher, and the
# one file of the repository that is deliberately not text.
SKIPPED_SUFFIXES = frozenset({".pdf"})

# Written as a code point so that the character itself never enters a source
# file of this repository, which is the rule the checks below enforce.
EM_DASH = chr(0x2014)

# The names are spelled in pieces for the same reason: each check below looks
# for a word that no file of this repository is allowed to hold, and no piece is
# a name of its own. The chat prefixed spelling comes before the bare one so
# that the whole word is what a failure reports.
ASSISTANT_NAMES = (
    "cla" + "ude",
    "anthro" + "pic",
    "open" + "ai",
    "chat" + "gp" + "t",
    "gp" + "t",
    "copi" + "lot",
)
# A letter before the name clears the match, so that an ordinary English word
# that holds one of them is left alone. A digit after it does not, because the
# version number of a model is written straight onto its name.
ASSISTANT_WORDS = re.compile(r"\b(" + "|".join(ASSISTANT_NAMES) + r")(?![A-Za-z])", re.IGNORECASE)
ASSISTANT_PHRASE = "generated by " + "ai"

# The two markers that open and close a fenced code block. They are built
# rather than written so that this file holds no fence of its own, which would
# read as an open block when the sweep comes round to this file.
FENCES = ("`" * 3, "~" * 3)

# The characters a line of hyphens is allowed to hold: the hyphens themselves,
# and the pipes, colons and spaces of a Markdown table separator row.
HYPHEN_LINE_CHARACTERS = frozenset("-|: ")
MINIMUM_HYPHENS = 3


def read(path: str | Path) -> str:
    """Return the text of one file of the repository.

    Parameters
    ----------
    path : str or pathlib.Path
        A path relative to the repository root, such as ``"README.md"``, or an
        absolute path, which is read as it stands.

    Returns
    -------
    str
        The content of the file, decoded as UTF-8.
    """
    return (ROOT / path).read_text(encoding="utf-8")


def load_yaml(path: str | Path) -> dict[str, Any]:
    """Return one parsed YAML file of the repository.

    Parameters
    ----------
    path : str or pathlib.Path
        The file to read, as ``read`` takes it.

    Returns
    -------
    dict
        The mapping the document holds.
    """
    return cast("dict[str, Any]", yaml.safe_load(read(path)))


def load_json(path: str | Path) -> dict[str, Any]:
    """Return one parsed JSON file of the repository.

    Parameters
    ----------
    path : str or pathlib.Path
        The file to read, as ``read`` takes it.

    Returns
    -------
    dict
        The mapping the document holds.
    """
    return cast("dict[str, Any]", json.loads(read(path)))


def load_workflow(name: str) -> dict[Any, Any]:
    """Return one parsed workflow file of .github/workflows.

    The keys are not all strings: YAML reads the unquoted workflow key ``on``
    as the boolean True, which is how the triggers are addressed by the tests.

    Parameters
    ----------
    name : str
        The file name inside ``.github/workflows``, such as ``"ci.yml"``.

    Returns
    -------
    dict
        The mapping the workflow holds, keys as YAML read them.
    """
    return cast("dict[Any, Any]", yaml.safe_load(read(WORKFLOWS / name)))


def flatten(text: str) -> str:
    """Return text with blockquote markers dropped and the spacing flattened.

    A sentence quoted in two places is free to wrap differently in each, and a
    quoted paragraph is free to carry its blockquote markers, so both are taken
    out of the way before the two are compared.

    Parameters
    ----------
    text : str
        The text to flatten.

    Returns
    -------
    str
        One line, with every run of whitespace collapsed to a single space.
    """
    lines = [line.strip().removeprefix(">").strip() for line in text.splitlines()]
    return " ".join(" ".join(lines).split())


def gitignored_paths(root: Path = ROOT) -> frozenset[str]:
    """Return the paths .gitignore names outright.

    Only the plain entries are read, the ones that are a path and nothing else.
    A pattern is left to git, which is the only thing that reads them all
    correctly. The plain entries are enough for the sweep: they are what keeps
    the local planning notes and any generated output directory out of the
    walk, while a tracked file of the same kind, such as the implementation
    plan, stays in. A packaged checkout, an unpacked sdist for one, ships no
    .gitignore, and then nothing is left out: what the file names is not in the
    archive either.

    Parameters
    ----------
    root : pathlib.Path, optional
        The directory holding the .gitignore to read. Default the repository
        root; a test passes a directory of its own instead.

    Returns
    -------
    frozenset of str
        Paths relative to ``root``, in POSIX form, without a trailing slash.
    """
    if not (root / GITIGNORE).is_file():
        return frozenset()
    entries = set()
    for line in (root / GITIGNORE).read_text(encoding="utf-8").splitlines():
        entry = line.strip()
        if not entry or entry.startswith("#") or any(mark in entry for mark in "*?[]!"):
            continue
        entries.add(entry.strip("/"))
    return frozenset(entries)


@cache
def text_files(root: Path = ROOT) -> dict[Path, str]:
    """Return every text file of one directory tree, with its content.

    The walk starts at ``root`` and skips the directories that hold nothing
    written by hand, the paths .gitignore names, the publisher PDF and anything
    that cannot be read as UTF-8 text, which is how a binary file is recognised
    without a guess at its type. A file the operating system refuses to hand
    over, a broken symbolic link for one, is skipped the same way, so that the
    state of one machine cannot take the house style checks down with it.

    The result is read once per root and kept, since a sweep asks for it several
    times over. Treat what comes back as read only.

    Parameters
    ----------
    root : pathlib.Path, optional
        The directory to walk. Default the repository root.

    Returns
    -------
    dict
        The absolute path of each file, mapped to its content.
    """
    ignored = gitignored_paths(root)
    files: dict[Path, str] = {}
    for folder, folders, names in os.walk(root):
        here = Path(folder)
        folders[:] = sorted(
            name
            for name in folders
            if name not in SKIPPED_DIRECTORIES
            and (here / name).relative_to(root).as_posix() not in ignored
        )
        for name in sorted(names):
            path = here / name
            if path.suffix in SKIPPED_SUFFIXES or path.relative_to(root).as_posix() in ignored:
                continue
            try:
                files[path] = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
    return files


def em_dash_lines(text: str) -> list[int]:
    """Return the number of every line that holds an em dash.

    Parameters
    ----------
    text : str
        The text to check.

    Returns
    -------
    list of int
        Line numbers, counted from one.
    """
    return [number for number, line in enumerate(text.splitlines(), 1) if EM_DASH in line]


def contains_em_dash(text: str) -> bool:
    """Return whether the text holds an em dash anywhere.

    Parameters
    ----------
    text : str
        The text to check.

    Returns
    -------
    bool
        True when the character appears at least once.
    """
    return EM_DASH in text


def three_hyphen_lines(text: str, *, python_source: bool = False) -> list[int]:
    """Return the number of every line that is a run of hyphens.

    A line counts when it holds three or more hyphens and nothing but hyphens,
    pipes, colons and spaces. Three kinds of such a line are not a violation:

    - a Markdown table separator row, which is the same shape with a pipe in
      it, as in a row of hyphens between two columns;
    - a line inside a fenced code block, where the text is a quoted example
      rather than prose of this repository. A block runs from its marker to the
      next line that opens with the same marker, so that a block of backticks
      holding a line of tildes, or the other way round, is read as one block;
    - a docstring section underline, which is a run of hyphens directly under a
      title line of the same length inside a Python file, as under Parameters
      or See Also. That exception is offered only when ``python_source`` says
      the text is Python, because the same two lines in Markdown are a setext
      heading, and the pages of this repository are written with the hash form
      instead.

    Parameters
    ----------
    text : str
        The text to check.
    python_source : bool, optional
        Whether the text is the source of a Python file, in which case a
        section underline is allowed. Default False.

    Returns
    -------
    list of int
        Line numbers, counted from one.
    """
    found: list[int] = []
    opener: str | None = None
    previous = ""
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if opener is None and stripped.startswith(FENCES):
            opener = stripped[: len(FENCES[0])]
        elif opener is not None and stripped.startswith(opener):
            opener = None
        elif _is_hyphen_line(stripped) and not _is_allowed_hyphen_line(
            stripped, previous, fenced=opener is not None, python_source=python_source
        ):
            found.append(number)
        previous = stripped
    return found


def has_three_hyphen_line(text: str, *, python_source: bool = False) -> bool:
    """Return whether the text holds a line of hyphens that is a violation.

    Parameters
    ----------
    text : str
        The text to check.
    python_source : bool, optional
        Whether the text is the source of a Python file. Default False. See
        ``three_hyphen_lines`` for what the flag allows and what it does not.

    Returns
    -------
    bool
        True when at least one line is a run of hyphens that no exception
        covers.
    """
    return bool(three_hyphen_lines(text, python_source=python_source))


def assistant_mention_lines(text: str) -> list[int]:
    """Return the number of every line that names an assistant or a model.

    The names are matched without regard to case, and the two ends of a name are
    treated differently. A letter before it clears the match, so that an
    ordinary English word holding one of them, philanthropic for one, is left
    alone. A letter after it clears the match too, but a digit does not, because
    a model is commonly named with its version number written straight onto it.
    The phrase that claims a machine wrote the file is matched as it is written,
    on one line.

    Parameters
    ----------
    text : str
        The text to check.

    Returns
    -------
    list of int
        Line numbers, counted from one.
    """
    return [
        number
        for number, line in enumerate(text.splitlines(), 1)
        if ASSISTANT_WORDS.search(line) or ASSISTANT_PHRASE in line.lower()
    ]


def single_trailing_space_lines(text: str) -> list[int]:
    """Return the number of every line that ends in exactly one space.

    Two trailing spaces are a hard line break in Markdown and are left alone.
    One is a slip of the keyboard that no reader ever sees.

    Parameters
    ----------
    text : str
        The text to check.

    Returns
    -------
    list of int
        Line numbers, counted from one.
    """
    return [
        number
        for number, line in enumerate(text.splitlines(), 1)
        if line.endswith(" ") and not line.endswith("  ")
    ]


def _is_hyphen_line(stripped: str) -> bool:
    """Return whether a stripped line is a run of hyphens and nothing else."""
    return stripped.count("-") >= MINIMUM_HYPHENS and set(stripped) <= HYPHEN_LINE_CHARACTERS


def _is_allowed_hyphen_line(
    stripped: str, previous: str, *, fenced: bool, python_source: bool
) -> bool:
    """Return whether one of the three exceptions covers a line of hyphens."""
    table_row = "|" in stripped
    section_underline = python_source and _underlines_a_title(stripped, previous)
    return fenced or table_row or section_underline


def _underlines_a_title(stripped: str, previous: str) -> bool:
    """Return whether a line of hyphens underlines the title of a docstring section.

    A section underline runs the length of the title above it, which is the
    convention numpydoc asks for and the ruff docstring rules enforce. Holding
    the underline to that length is what tells a section apart from a rule of
    hyphens drawn under a line of prose or of code.
    """
    return (
        len(stripped) == len(previous)
        and set(stripped) == {"-"}
        and any(character.isalpha() for character in previous)
    )
